version: '3.3'

services:
  frontend:
    container_name: take-some-rest-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - take-some-rest

  backend:
    container_name: take-some-rest-backend
    build:
      context: backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5000:5000
    networks:
      - take-some-rest

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  my_network:
    external: true
