version: '3.3'

services:
  backend:
    image: take-some-rest-backend
    build: ./backend
    container_name: take-some-rest-backend
    restart: always
    ports:
      - 5000:5000

  frontend:
    image: take-some-rest-frontend
    build: ./frontend
    container_name: take-some-rest-frontend
    restart: always
    ports:
      - 3000:3000
